dev.getelements.elements.app.serve.prefix=oncade
dev.getelements.elements.auth.enabled=true
dev.getelements.elements.mongo.uri=mongodb://mongo:27017/elements?retryWrites=true&w=majority
#dev.getelements.elements.mongo.uri=mongodb://localhost:27017/?retryWrites=true&w=majority

# xyz.oncade.http.client.url=http://localhost:3000/api/v1
xyz.oncade.http.client.url=http://host.docker.internal:3000/api/v1
xyz.oncade.http.client.timeout=30000
xyz.oncade.http.client.debug=true
xyz.oncade.http.client.apiKey=oncade_live_5f1bd3677232a2208cef8a58bd19c4d1a5078a2a6fb774300ea05dc5997647a1
xyz.oncade.http.webhook.secret=31c750289e2edd84ab8c6209b35d99ebc99b36ebbc23546ed446899c83a0f58b